export const array = [
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    },
    {
        idProduct: 1,
        name: "Esm. Agua Blanco Brill int. x 1/2 L",
        price: 8573,
        code: "001-AGUA0500",
        category: "Linea Ecologica",
        patent: "FADEPA",
        image: "https://res.cloudinary.com/dz8e0hmgg/image/upload/v1694748514/esm_al%2520agua.JPG.jpg",
        featured: false,
        package: "1/2 lts.",
        stock: 3,
        promotion: null,
        color: "Blanco brillante",
        rating: 5,
        active: true,
        description: "ideal para pintar objetos a los que quiera dar la máxima protección y el más perfecto acabado. Su pelicula lisa, brillante y dura, proporciona efectos decorativos de gran jerarquía. Es aplicable tanto en interior como exterior sobre superficies de mampostería, madera o metal ",
        nroReviews: 0,
        providerId: 1
    }
]
