name: eslint-check

run-name: eslint-check

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install eslint
        run: pnpm install --global eslint eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard

      - name: Lint with ESLint
        run: pnpm lint
